Format shell scripts with shfmt.
All changes in this patch were performed automatically with `shfmt` with
configuration flags specified in `.pre-commit-config.yaml`.

In addition to fixing whitespace the roundtrip through shfmt's AST also
transforms command substitutions

    `cmd`
    # becomes
    $(cmd)

and some redirects

    >&2 echo "msg"
    # becomes
    echo >&2 "msg"

diff --git a/testing/scripts/wait-for-file b/testing/scripts/wait-for-file
--- a/testing/scripts/wait-for-file
+++ b/testing/scripts/wait-for-file
@@ -3,8 +3,8 @@
 # Sleeps until a file comes into existence.
 
 if [[ $# -ne 2 ]]; then
-  >&2 echo "usage: $0 <file to wait for> <max secs to wait>"
-  exit 1
+    echo >&2 "usage: $0 <file to wait for> <max secs to wait>"
+    exit 1
 fi
 
 wait_file=$1
@@ -12,13 +12,12 @@ max_wait=$2
 wait_count=0
 
 while [[ ! -e $wait_file ]]; do
-  let "wait_count += 1"
+    let "wait_count += 1"
 
-  if [[ $wait_count -ge $max_wait ]]; then
-    >&2 echo "error: file '$wait_file' does not exist after $max_wait seconds"
-    exit 1
-  fi
+    if [[ $wait_count -ge $max_wait ]]; then
+        echo >&2 "error: file '$wait_file' does not exist after $max_wait seconds"
+        exit 1
+    fi
 
-  sleep 1
+    sleep 1
 done
-
